### ISSUE TITLE
Not working on Ubuntu nor windows 

### ISSUE THREAD

**Issue by amgno** [Saren-Arterius/aroz-dockerize#6]
2022/08/01 18:51:07 ArozOS(C) 2021 IMUSLAB.INC.
2022/08/01 18:51:07 ArozOS development Revision 0.1.123
2022/08/01 18:51:07 Key-value Database Service Started: system/ao.db
2022/08/01 18:51:07 New authentication session key generated
panic: *ERROR* Failed to create database for login tracking: open ./system/auth/authlog.db: no such file or directory

goroutine 1 [running]:
imuslab.com/arozos/mod/auth.NewAuthenticationAgent({0xd72d21, 0x7}, {0xc00012d950?, 0xd7736d?, 0xa?}, 0xc000233000, 0x40?, 0xdd1c80)
	/arozos/src/mod/auth/auth.go:105 +0x39f
main.AuthInit()
	/arozos/src/auth.go:34 +0x205
main.RunStartup()
	/arozos/src/startup.go:56 +0x1b7
main.main()
	/arozos/src/main.go:107 +0x330
2022/08/01 18:51:09 ArozOS(C) 2021 IMUSLAB.INC.
2022/08/01 18:51:09 ArozOS development Revision 0.1.123
2022/08/01 18:51:09 Key-value Database Service Started: system/ao.db
2022/08/01 18:51:09 Authentication session key loaded from database
panic: *ERROR* Failed to create database for login tracking: open ./system/auth/authlog.db: no such file or directory

goroutine 1 [running]:
imuslab.com/arozos/mod/auth.NewAuthenticationAgent({0xd72d21, 0x7}, {0xc000127920?, 0xd7736d?, 0xa?}, 0xc0002290c0, 0x50?, 0xdd1c80)
	/arozos/src/mod/auth/auth.go:105 +0x39f
main.AuthInit()
	/arozos/src/auth.go:34 +0x205
main.RunStartup()
	/arozos/src/startup.go:56 +0x1b7
main.main()
	/arozos/src/main.go:107 +0x330
2022/08/01 18:51:11 ArozOS(C) 2021 IMUSLAB.INC.
2022/08/01 18:51:11 ArozOS development Revision 0.1.123
2022/08/01 18:51:11 Key-value Database Service Started: system/ao.db
2022/08/01 18:51:11 Authentication session key loaded from database
panic: *ERROR* Failed to create database for login tracking: open ./system/auth/authlog.db: no such file or directory

goroutine 1 [running]:
imuslab.com/arozos/mod/auth.NewAuthenticationAgent({0xd72d21, 0x7}, {0xc0002ae0f0?, 0xd7736d?, 0xa?}, 0xc0002ba0c0, 0x40?, 0xdd1c80)
	/arozos/src/mod/auth/auth.go:105 +0x39f
main.AuthInit()
	/arozos/src/auth.go:34 +0x205
main.RunStartup()
	/arozos/src/startup.go:56 +0x1b7
main.main()
	/arozos/src/main.go:107 +0x330
2022/08/01 18:51:12 ArozOS(C) 2021 IMUSLAB.INC.
2022/08/01 18:51:12 ArozOS development Revision 0.1.123
2022/08/01 18:51:12 Key-value Database Service Started: system/ao.db
2022/08/01 18:51:12 Authentication session key loaded from database
panic: *ERROR* Failed to create database for login tracking: open ./system/auth/authlog.db: no such file or directory

goroutine 1 [running]:
imuslab.com/arozos/mod/auth.NewAuthenticationAgent({0xd72d21, 0x7}, {0xc000115950?, 0xd7736d?, 0xa?}, 0xc00020b100, 0x80?, 0xdd1c80)
	/arozos/src/mod/auth/auth.go:105 +0x39f
main.AuthInit()
	/arozos/src/auth.go:34 +0x205
main.RunStartup()
	/arozos/src/startup.go:56 +0x1b7
main.main()
	/arozos/src/main.go:107 +0x330
2022/08/01 18:51:14 ArozOS(C) 2021 IMUSLAB.INC.
2022/08/01 18:51:14 ArozOS development Revision 0.1.123
2022/08/01 18:51:14 Key-value Database Service Started: system/ao.db
2022/08/01 18:51:14 Authentication session key loaded from database
panic: *ERROR* Failed to create database for login tracking: open ./system/auth/authlog.db: no such file or directory

goroutine 1 [running]:
imuslab.com/arozos/mod/auth.NewAuthenticationAgent({0xd72d21, 0x7}, {0xc0002ae0f0?, 0xd7736d?, 0xa?}, 0xc0002ba0c0, 0x40?, 0xdd1c80)
	/arozos/src/mod/auth/auth.go:105 +0x39f
main.AuthInit()
	/arozos/src/auth.go:34 +0x205
main.RunStartup()
	/arozos/src/startup.go:56 +0x1b7
main.main()
	/arozos/src/main.go:107 +0x330
2022/08/01 18:51:17 ArozOS(C) 2021 IMUSLAB.INC.
2022/08/01 18:51:17 ArozOS development Revision 0.1.123
2022/08/01 18:51:17 Key-value Database Service Started: system/ao.db
2022/08/01 18:51:17 Authentication session key loaded from database
panic: *ERROR* Failed to create database for login tracking: open ./system/auth/authlog.db: no such file or directory

goroutine 1 [running]:
imuslab.com/arozos/mod/auth.NewAuthenticationAgent({0xd72d21, 0x7}, {0xc0002a20f0?, 0xd7736d?, 0xa?}, 0xc0002ae0c0, 0x40?, 0xdd1c80)
	/arozos/src/mod/auth/auth.go:105 +0x39f
main.AuthInit()
	/arozos/src/auth.go:34 +0x205
main.RunStartup()
	/arozos/src/startup.go:56 +0x1b7
main.main()
	/arozos/src/main.go:107 +0x330
2022/08/01 18:51:22 ArozOS(C) 2021 IMUSLAB.INC.
2022/08/01 18:51:22 ArozOS development Revision 0.1.123
2022/08/01 18:51:22 Key-value Database Service Started: system/ao.db
2022/08/01 18:51:22 Authentication session key loaded from database
panic: *ERROR* Failed to create database for login tracking: open ./system/auth/authlog.db: no such file or directory

goroutine 1 [running]:
imuslab.com/arozos/mod/auth.NewAuthenticationAgent({0xd72d21, 0x7}, {0xc0002920f0?, 0xd7736d?, 0xa?}, 0xc00007a100, 0x70?, 0xdd1c80)
	/arozos/src/mod/auth/auth.go:105 +0x39f
main.AuthInit()
	/arozos/src/auth.go:34 +0x205
main.RunStartup()
	/arozos/src/startup.go:56 +0x1b7
main.main()
	/arozos/src/main.go:107 +0x330
2022/08/01 18:51:29 ArozOS(C) 2021 IMUSLAB.INC.
2022/08/01 18:51:29 ArozOS development Revision 0.1.123
2022/08/01 18:51:29 Key-value Database Service Started: system/ao.db
2022/08/01 18:51:29 Authentication session key loaded from database
panic: *ERROR* Failed to create database for login tracking: open ./system/auth/authlog.db: no such file or directory

goroutine 1 [running]:
imuslab.com/arozos/mod/auth.NewAuthenticationAgent({0xd72d21, 0x7}, {0xc0000b5920?, 0xd7736d?, 0xa?}, 0xc0001b90c0, 0x50?, 0xdd1c80)
	/arozos/src/mod/auth/auth.go:105 +0x39f
main.AuthInit()
	/arozos/src/auth.go:34 +0x205
main.RunStartup()
	/arozos/src/startup.go:56 +0x1b7
main.main()
	/arozos/src/main.go:107 +0x330
2022/08/01 18:51:43 ArozOS(C) 2021 IMUSLAB.INC.
2022/08/01 18:51:43 ArozOS development Revision 0.1.123
2022/08/01 18:51:43 Key-value Database Service Started: system/ao.db
2022/08/01 18:51:43 Authentication session key loaded from database
panic: *ERROR* Failed to create database for login tracking: open ./system/auth/authlog.db: no such file or directory

goroutine 1 [running]:
imuslab.com/arozos/mod/auth.NewAuthenticationAgent({0xd72d21, 0x7}, {0xc0003220f0?, 0xd7736d?, 0xa?}, 0xc00032e0c0, 0x40?, 0xdd1c80)
	/arozos/src/mod/auth/auth.go:105 +0x39f
main.AuthInit()
	/arozos/src/auth.go:34 +0x205
main.RunStartup()
	/arozos/src/startup.go:56 +0x1b7
main.main()
	/arozos/src/main.go:107 +0x330
2022/08/01 18:52:10 ArozOS(C) 2021 IMUSLAB.INC.
2022/08/01 18:52:10 ArozOS development Revision 0.1.123
2022/08/01 18:52:10 Key-value Database Service Started: system/ao.db
2022/08/01 18:52:10 Authentication session key loaded from database
panic: *ERROR* Failed to create database for login tracking: open ./system/auth/authlog.db: no such file or directory

goroutine 1 [running]:
imuslab.com/arozos/mod/auth.NewAuthenticationAgent({0xd72d21, 0x7}, {0xc0000bc0f0?, 0xd7736d?, 0xa?}, 0xc0000c80c0, 0x20?, 0xdd1c80)
	/arozos/src/mod/auth/auth.go:105 +0x39f
main.AuthInit()
	/arozos/src/auth.go:34 +0x205
main.RunStartup()
	/arozos/src/startup.go:56 +0x1b7
main.main()
	/arozos/src/main.go:107 +0x330
2022/08/01 18:51:07 ArozOS(C) 2021 IMUSLAB.INC.
2022/08/01 18:51:07 ArozOS development Revision 0.1.123
2022/08/01 18:51:07 Key-value Database Service Started: system/ao.db
2022/08/01 18:51:07 New authentication session key generated
panic: *ERROR* Failed to create database for login tracking: open ./system/auth/authlog.db: no such file or directory

goroutine 1 [running]:
imuslab.com/arozos/mod/auth.NewAuthenticationAgent({0xd72d21, 0x7}, {0xc00012d950?, 0xd7736d?, 0xa?}, 0xc000233000, 0x40?, 0xdd1c80)
	/arozos/src/mod/auth/auth.go:105 +0x39f
main.AuthInit()
	/arozos/src/auth.go:34 +0x205
main.RunStartup()
	/arozos/src/startup.go:56 +0x1b7
main.main()
	/arozos/src/main.go:107 +0x330
2022/08/01 18:51:09 ArozOS(C) 2021 IMUSLAB.INC.
2022/08/01 18:51:09 ArozOS development Revision 0.1.123
2022/08/01 18:51:09 Key-value Database Service Started: system/ao.db
2022/08/01 18:51:09 Authentication session key loaded from database
panic: *ERROR* Failed to create database for login tracking: open ./system/auth/authlog.db: no such file or directory

goroutine 1 [running]:
imuslab.com/arozos/mod/auth.NewAuthenticationAgent({0xd72d21, 0x7}, {0xc000127920?, 0xd7736d?, 0xa?}, 0xc0002290c0, 0x50?, 0xdd1c80)
	/arozos/src/mod/auth/auth.go:105 +0x39f
main.AuthInit()
	/arozos/src/auth.go:34 +0x205
main.RunStartup()
	/arozos/src/startup.go:56 +0x1b7
main.main()
	/arozos/src/main.go:107 +0x330
2022/08/01 18:51:11 ArozOS(C) 2021 IMUSLAB.INC.
2022/08/01 18:51:11 ArozOS development Revision 0.1.123
2022/08/01 18:51:11 Key-value Database Service Started: system/ao.db
2022/08/01 18:51:11 Authentication session key loaded from database
panic: *ERROR* Failed to create database for login tracking: open ./system/auth/authlog.db: no such file or directory

goroutine 1 [running]:
imuslab.com/arozos/mod/auth.NewAuthenticationAgent({0xd72d21, 0x7}, {0xc0002ae0f0?, 0xd7736d?, 0xa?}, 0xc0002ba0c0, 0x40?, 0xdd1c80)
	/arozos/src/mod/auth/auth.go:105 +0x39f
main.AuthInit()
	/arozos/src/auth.go:34 +0x205
main.RunStartup()
	/arozos/src/startup.go:56 +0x1b7
main.main()
	/arozos/src/main.go:107 +0x330
2022/08/01 18:51:12 ArozOS(C) 2021 IMUSLAB.INC.
2022/08/01 18:51:12 ArozOS development Revision 0.1.123
2022/08/01 18:51:12 Key-value Database Service Started: system/ao.db
2022/08/01 18:51:12 Authentication session key loaded from database
panic: *ERROR* Failed to create database for login tracking: open ./system/auth/authlog.db: no such file or directory

goroutine 1 [running]:
imuslab.com/arozos/mod/auth.NewAuthenticationAgent({0xd72d21, 0x7}, {0xc000115950?, 0xd7736d?, 0xa?}, 0xc00020b100, 0x80?, 0xdd1c80)
	/arozos/src/mod/auth/auth.go:105 +0x39f
main.AuthInit()
	/arozos/src/auth.go:34 +0x205
main.RunStartup()
	/arozos/src/startup.go:56 +0x1b7
main.main()
	/arozos/src/main.go:107 +0x330
2022/08/01 18:51:14 ArozOS(C) 2021 IMUSLAB.INC.
2022/08/01 18:51:14 ArozOS development Revision 0.1.123
2022/08/01 18:51:14 Key-value Database Service Started: system/ao.db
2022/08/01 18:51:14 Authentication session key loaded from database
panic: *ERROR* Failed to create database for login tracking: open ./system/auth/authlog.db: no such file or directory

goroutine 1 [running]:
imuslab.com/arozos/mod/auth.NewAuthenticationAgent({0xd72d21, 0x7}, {0xc0002ae0f0?, 0xd7736d?, 0xa?}, 0xc0002ba0c0, 0x40?, 0xdd1c80)
	/arozos/src/mod/auth/auth.go:105 +0x39f
main.AuthInit()
	/arozos/src/auth.go:34 +0x205
main.RunStartup()
	/arozos/src/startup.go:56 +0x1b7
main.main()
	/arozos/src/main.go:107 +0x330
2022/08/01 18:51:17 ArozOS(C) 2021 IMUSLAB.INC.
2022/08/01 18:51:17 ArozOS development Revision 0.1.123
2022/08/01 18:51:17 Key-value Database Service Started: system/ao.db
2022/08/01 18:51:17 Authentication session key loaded from database
panic: *ERROR* Failed to create database for login tracking: open ./system/auth/authlog.db: no such file or directory

goroutine 1 [running]:
imuslab.com/arozos/mod/auth.NewAuthenticationAgent({0xd72d21, 0x7}, {0xc0002a20f0?, 0xd7736d?, 0xa?}, 0xc0002ae0c0, 0x40?, 0xdd1c80)
	/arozos/src/mod/auth/auth.go:105 +0x39f
main.AuthInit()
	/arozos/src/auth.go:34 +0x205
main.RunStartup()
	/arozos/src/startup.go:56 +0x1b7
main.main()
	/arozos/src/main.go:107 +0x330
2022/08/01 18:51:22 ArozOS(C) 2021 IMUSLAB.INC.
2022/08/01 18:51:22 ArozOS development Revision 0.1.123
2022/08/01 18:51:22 Key-value Database Service Started: system/ao.db
2022/08/01 18:51:22 Authentication session key loaded from database
panic: *ERROR* Failed to create database for login tracking: open ./system/auth/authlog.db: no such file or directory

goroutine 1 [running]:
imuslab.com/arozos/mod/auth.NewAuthenticationAgent({0xd72d21, 0x7}, {0xc0002920f0?, 0xd7736d?, 0xa?}, 0xc00007a100, 0x70?, 0xdd1c80)
	/arozos/src/mod/auth/auth.go:105 +0x39f
main.AuthInit()
	/arozos/src/auth.go:34 +0x205
main.RunStartup()
	/arozos/src/startup.go:56 +0x1b7
main.main()
	/arozos/src/main.go:107 +0x330
2022/08/01 18:51:29 ArozOS(C) 2021 IMUSLAB.INC.
2022/08/01 18:51:29 ArozOS development Revision 0.1.123
2022/08/01 18:51:29 Key-value Database Service Started: system/ao.db
2022/08/01 18:51:29 Authentication session key loaded from database
panic: *ERROR* Failed to create database for login tracking: open ./system/auth/authlog.db: no such file or directory

goroutine 1 [running]:
imuslab.com/arozos/mod/auth.NewAuthenticationAgent({0xd72d21, 0x7}, {0xc0000b5920?, 0xd7736d?, 0xa?}, 0xc0001b90c0, 0x50?, 0xdd1c80)
	/arozos/src/mod/auth/auth.go:105 +0x39f
main.AuthInit()
	/arozos/src/auth.go:34 +0x205
main.RunStartup()
	/arozos/src/startup.go:56 +0x1b7
main.main()
	/arozos/src/main.go:107 +0x330
2022/08/01 18:51:43 ArozOS(C) 2021 IMUSLAB.INC.
2022/08/01 18:51:43 ArozOS development Revision 0.1.123
2022/08/01 18:51:43 Key-value Database Service Started: system/ao.db
2022/08/01 18:51:43 Authentication session key loaded from database
panic: *ERROR* Failed to create database for login tracking: open ./system/auth/authlog.db: no such file or directory

goroutine 1 [running]:
imuslab.com/arozos/mod/auth.NewAuthenticationAgent({0xd72d21, 0x7}, {0xc0003220f0?, 0xd7736d?, 0xa?}, 0xc00032e0c0, 0x40?, 0xdd1c80)
	/arozos/src/mod/auth/auth.go:105 +0x39f
main.AuthInit()
	/arozos/src/auth.go:34 +0x205
main.RunStartup()
	/arozos/src/startup.go:56 +0x1b7
main.main()
	/arozos/src/main.go:107 +0x330
2022/08/01 18:52:10 ArozOS(C) 2021 IMUSLAB.INC.
2022/08/01 18:52:10 ArozOS development Revision 0.1.123
2022/08/01 18:52:10 Key-value Database Service Started: system/ao.db
2022/08/01 18:52:10 Authentication session key loaded from database
panic: *ERROR* Failed to create database for login tracking: open ./system/auth/authlog.db: no such file or directory

goroutine 1 [running]:
imuslab.com/arozos/mod/auth.NewAuthenticationAgent({0xd72d21, 0x7}, {0xc0000bc0f0?, 0xd7736d?, 0xa?}, 0xc0000c80c0, 0x20?, 0xdd1c80)
	/arozos/src/mod/auth/auth.go:105 +0x39f
main.AuthInit()
	/arozos/src/auth.go:34 +0x205
main.RunStartup()
	/arozos/src/startup.go:56 +0x1b7
main.main()
	/arozos/src/main.go:107 +0x330
2022/08/01 18:53:03 ArozOS(C) 2021 IMUSLAB.INC.
2022/08/01 18:53:03 ArozOS development Revision 0.1.123
2022/08/01 18:53:03 Key-value Database Service Started: system/ao.db
2022/08/01 18:53:03 Authentication session key loaded from database
panic: *ERROR* Failed to create database for login tracking: open ./system/auth/authlog.db: no such file or directory

goroutine 1 [running]:
imuslab.com/arozos/mod/auth.NewAuthenticationAgent({0xd72d21, 0x7}, {0xc0002ae0f0?, 0xd7736d?, 0xa?}, 0xc0002ba0c0, 0x40?, 0xdd1c80)
	/arozos/src/mod/auth/auth.go:105 +0x39f
main.AuthInit()
	/arozos/src/auth.go:34 +0x205
main.RunStartup()
	/arozos/src/startup.go:56 +0x1b7
main.main()
	/arozos/src/main.go:107 +0x330

**Comment by GabyPCgeeK** [comment]
needs named volume for at least /arozos/src/system
